apiVersion: v1   
kind: Pod                
metadata:       
  name: sunhttpdpod
  namespace: default
  labels:                      
    name: sunhttpdpod            
spec:
  containers:
  - name: qinhttpd24
    image: registry:5000/sunimages/httpd:2.4
    env:
    - name: sunenv1
      value: sun1
    - name: sunenv2
      value: sun2
    ports:
    - containerPort: 80
      hostPort: 80
